### ISSUE TITLE
[Exact search grid for gamma1 and gamma2]

### ISSUE THREAD

**Issue by hyusterr** [psm1206/MAWU#1]
As title, I'm wondering how did you set the search grid or your search method for the hyperparameters, the paper provide only the scope, which is a bit confusing when I tried to reproduce the result.

**Comment by psm1206** [comment]
Thank you for your interest in our paper.

Basically, we adjusted the gamma1 and gamma2 depending on the datasets.
1) Beauty: [0, 2] with step size 0.1
2) Gowalla: [0, 5] with step size 0.4
3) Yelp2018: [0, 2] with step size 0.3

If you have any questions, please feel free to contact me.

Thank you.

**Comment by hyusterr** [comment]
thanks for your reply!
